mensautils/base/urls.py
from django.conf.urls import url

from mensautils.base import views

app_name = 'mensautils.base'
urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^stats/$', views.stats, name='stats'),
]

mensautils/canteen/urls.py
from django.conf.urls import url
from rest_framework.routers import DefaultRouter

from mensautils.canteen import views

app_name = 'mensautils.canteen'
urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^userconfig/save/$', views.save_canteen_user_config,
        name='save_canteen_user_config'),
    url(r'^stats/$', views.stats, name='stats'),
    url(r'^rate/(\d+)/$', views.rate_serving, name='rate_serving'),
    url(r'^deprecate/(\d+)/$', views.report_deprecation, name='report_deprecation'),
    url(r'^submit/(\d+)/$', views.submit_serving, name='submit_serving'),
    url(r'^verify/(\d+)/$', views.verify_serving, name='verify_serving'),
    url(r'^notification/$', views.notification, name='notification'),
    url(r'^notification/(\d+)/delete/$', views.delete_notification,
        name='delete_notification'),
    url(r'^notification/add/$', views.add_notification, name='add_notification'),
]

router = DefaultRouter()
router.register(r'api/canteens', views.CanteenViewSet, basename='canteens')
urlpatterns += router.urls

mensautils/urls.py
from django.conf import settings
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.auth import views as auth_views

from rest_framework.documentation import include_docs_urls

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url('^login/$', auth_views.LoginView.as_view(template_name='mensautils/login.html'),
        name='login'),
    url('^logout/$', auth_views.LogoutView.as_view(), name='logout'),
    url(r'^', include('mensautils.canteen.urls')),
    url(r'^docs/', include_docs_urls(title='Documentation', authentication_classes=[], permission_classes=[])),
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns += [
        url(r'^__debug__/', include(debug_toolbar.urls)),
    ]

mensautils/canteen/models.py
from django.conf import settings
from django.core.validators import MinValueValidator, MaxValueValidator
from django.db import models
from django.db.models import Avg, Count
from django.utils import timezone
from django.utils.translation import ugettext_lazy as _
from fuzzywuzzy import fuzz


class Dish(models.Model):
    name = models.CharField(verbose_name=_('name'), max_length=300)
    vegetarian = models.BooleanField()
    vegan = models.BooleanField()

    def __str__(self):
        return self.name

    @staticmethod
    def fuzzy_find_or_create(name: str, vegetarian: bool, vegan: bool) -> 'Dish':
        for dish in Dish.objects.filter(vegetarian=vegetarian, vegan=vegan):
            if fuzz.token_sort_ratio(name, dish.name) >= settings.FUZZY_MIN_RATIO:
                return dish
        return Dish.objects.create(name=name, vegetarian=vegetarian, vegan=vegan)


class Canteen(models.Model):
    name = models.CharField(verbose_name=_('name'), max_length=100)
    active = models.BooleanField(default=True)

    def __str__(self):
        return self.name


class OpeningTime(models.Model):
    class Meta:
        unique_together = ['canteen', 'weekday']

    canteen = models.ForeignKey(
        Canteen, on_delete=models.CASCADE, related_name='opening_times')
    weekday = models.IntegerField() # iso weekday, 1=monday, 7=sunday
    start = models.TimeField()
    end = models.TimeField()

    def __str__(self) -> str:
        return '{}: {} {}-{}'.format(
            self.canteen.name, self.weekday, self.start, self.end)

    @staticmethod
    def get_opening_time(canteen: Canteen, weekday: int) -> 'OpeningTime':
        """Get the opening time of a canteen on a weekday."""
        pass


class CanteenUserConfig(models.Model):
    user = models.OneToOneField(
        settings.AUTH_USER_MODEL, on_delete=models.CASCADE,
        related_name='canteen_config')
    order = models.CharField(max_length=100)
    hidden = models.CharField(max_length=100)

    def __str__(self):
        return '{}'.format(self.user)


class Serving(models.Model):
    date = models.DateField()
    dish = models.ForeignKey(
        Dish, on_delete=models.CASCADE, related_name='servings')
    canteen = models.ForeignKey(
        Canteen, on_delete=models.CASCADE, related_name='servings')
    price = models.DecimalField(max_digits=4, decimal_places=2)
    price_staff = models.DecimalField(max_digits=4, decimal_places=2)

    last_updated = models.DateTimeField(default=timezone.now)
    official = models.BooleanField(default=True)
    officially_deprecated = models.BooleanField(default=False)
    notified = models.BooleanField(default=False)

    def __str__(self):
        return '{}: {} ({}, {})'.format(self.canteen, str(self.dish), str(self.date),
                                        self.price)

    def average_rating(self) -> float:
        """Get average rating."""
        if hasattr(self, 'ratings__rating__avg'):
            return self.ratings__rating__avg
        return self.ratings.aggregate(Avg('rating'))['rating__avg']

    def rating_count(self) -> int:
        """Get rating count."""
        if hasattr(self, 'ratings__count'):
            return self.ratings__count
        return self.ratings.count()

    def verifications_count(self):
        if hasattr(self, 'verifications__count'):
            return self.verifications__count
        else:
            return self.verifications.count

    def deprecation_reports_count(self):
        if hasattr(self, 'deprecation_reports__count'):
            return self.deprecation_reports__count
        else:
            return self.aggregate(
                Count('deprecation_reports'))['deprecation_reports__count']

    @property
    def verified(self) -> bool:
        return (self.official or
                self.verifications_count() >= settings.MIN_REPORTS)

    @property
    def deprecated(self) -> bool:
        return (self.officially_deprecated or
                self.deprecation_reports_count() >= settings.MIN_REPORTS)

    @property
    def maybe_deprecated(self) -> bool:
        """Maybe deprecated when at least one user has reported serving."""
        reports = self.deprecation_reports_count()
        return reports >= 1


class Rating(models.Model):
    class Meta:
        unique_together = [('user', 'serving')]
    user = models.ForeignKey(
        settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='ratings')
    serving = models.ForeignKey(
        Serving, on_delete=models.CASCADE, related_name='ratings')
    rating = models.SmallIntegerField(
        validators=[MinValueValidator(1), MaxValueValidator(5)])

    def __str__(self):
        return '{}: {} ({})'.format(self.rating, str(self.serving), self.user)


class InofficialDeprecation(models.Model):
    """Deprecation reported by users."""
    class Meta:
        unique_together = [('serving', 'reporter')]
    serving = models.ForeignKey(
        Serving, on_delete=models.CASCADE, related_name='deprecation_reports')
    reporter = models.ForeignKey(
        settings.AUTH_USER_MODEL, on_delete=models.CASCADE,
        related_name='deprecation_reports')

    def __str__(self):
        return '{}: {}'.format(self.reporter, self.serving)


class ServingVerification(models.Model):
    """Verification for inofficial servings."""
    class Meta:
        unique_together = ['serving', 'user']
    serving = models.ForeignKey(
        Serving, on_delete=models.CASCADE, related_name='verifications')
    user = models.ForeignKey(
        settings.AUTH_USER_MODEL, on_delete=models.CASCADE,
        related_name='serving_verifications')
    reporter = models.BooleanField(default=False)

    def __str__(self):
        return '{} ({})'.format(self.serving, self.user)


class Notification(models.Model):
    """Notification for user to send."""
    class Meta:
        unique_together = ['user', 'pattern']
    user = models.ForeignKey(
        settings.AUTH_USER_MODEL, on_delete=models.CASCADE,
        related_name='notifications')
    pattern = models.CharField(max_length=300)

    added = models.DateTimeField(default=timezone.now)
    last_notified = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return '{} ({})'.format(self.pattern, self.user)

mensautils/canteen/forms.py
from django import forms


class RateForm(forms.Form):
    rating = forms.ChoiceField(choices=[(a, a) for a in  range(1, 6)])


class SubmitServingForm(forms.Form):
    name = forms.CharField(max_length=300)
    vegetarian = forms.BooleanField(required=False)
    vegan = forms.BooleanField(required=False)
    price = forms.DecimalField(max_digits=4, decimal_places=2)
    price_staff = forms.DecimalField(max_digits=4, decimal_places=2)


class NotificationForm(forms.Form):
    pattern = forms.CharField(max_length=300)

mensautils/base/views.py
from datetime import date, timedelta

from django.db.models import Max
from django.http import HttpRequest
from django.http import HttpResponse
from django.shortcuts import render
from django.utils import timezone

from mensautils.base.models import Canteen, Serving
from mensautils.base.statistics import get_most_frequent_dishes


def index(request: HttpRequest) -> HttpResponse:
    today = date.today()
    days = [today, today + timedelta(days=1)]
    canteens = Canteen.objects.order_by('name')
    canteen_data = {}
    for day in days:
        canteen_data[day] = {}
        for canteen in canteens:
            canteen_data[day][canteen.name] = canteen.servings.filter(
                date=day)
    return render(request, 'mensautils/mensa.html', {
        'today': today,
        'mensa_data': canteen_data,
        'last_updated': Serving.objects.aggregate(
            Max('last_updated'))['last_updated__max'],
    })


def stats(request: HttpRequest) -> HttpResponse:
    most_frequent_dishes = get_most_frequent_dishes()
    return render(
        request, 'mensautils/statistics.html', {
            'most_frequent_dishes': most_frequent_dishes,
        })

mensautils/canteen/templates/mensautils/add_notification.html
{% extends 'mensautils/base.html' %}
{% load static %}

{% block content %}
  <h1>Mensa-Speisepläne in Hamburg</h1>

  {% if request.user.is_authenticated %}
    <p>Hallo, <em>{{ request.user.username }}</em>.</p>
  {% endif %}

  <form method="POST" action="{{ request.get_full_path }}">
    {% csrf_token %}

    <p>Wähle eine Suchregel, anhand der Du Benachrichtigungen erhalten möchtest.</p>
    <p>Sobald eine Mensa ein Gericht in den Speiseplan aufnimmt, die den von Dir
      gewählten Ausdruck beinhaltet oder ihm ähnlich ist, erhältst Du eine
      E-Mail, die Dich auf die Mensa und das entsprechende Gericht hinweist.</p>

    {{ form.pattern }}

    <p>
      {% for error in form.pattern.errors %}
        {{ error }}<br />
      {% endfor %}
      {% for error in form.non_field_errors %}
        {{ error }}<br />
      {% endfor %}
    </p>

    <input type="submit" value="Benachrichtigung hinzufügen" />
  </form>

  <p>
    <a href="{% url 'mensautils.canteen:index' %}">Startseite</a> &bull;
    <a href="{% url 'mensautils.canteen:notification' %}">Benachrichtigungen</a>
  </p>
{% endblock content %}

mensautils/canteen/templates/mensautils/base.html
{% load static %}<!doctype html>
<html>
  <head>
    <meta http-equiv="Content-type" content="text/html; charset=utf-8" />

    <meta name="viewport" content="width=device-width, initial-scale=1" />

    <link rel="stylesheet" href="{% static 'mensautils/css/bootstrap.min.css' %}">

    <title>Mensa-Speisepläne in Hamburg</title>

    {% block additional_css %}
    {% endblock additional_css %}
  </head>
  <body>
    <div class="container-fluid" style="margin: 0.5em 1em;">
      {% for message in messages %}
        <div{% if message.tags %} class="alert alert-{{ message.tags }}"{% endif %}>
          {{ message }}
        </div>
      {% endfor %}

      {% block content %}
      {% endblock content %}

      <p>
        Powered by <a href="https://git.mafiasi.de/mafiasi-ag/mensa-utils">mensa-utils</a>.<br />
        Alle Angaben ohne Gewähr. <a href="https://mafiasi.de/base/imprint">Impressum</a>
      </p>
    </div>

    <script type="text/javascript" src="{% static 'mensautils/jquery.js' %}"></script>
    {% block additional_js %}
    {% endblock additional_js %}
  </body>
</html>

mensautils/canteen/templates/mensautils/delete_notification.html
{% extends 'mensautils/base.html' %}
{% load static %}

{% block content %}
  <h1>Mensa-Speisepläne in Hamburg</h1>

  {% if request.user.is_authenticated %}
    <p>Hallo, <em>{{ request.user.username }}</em>.</p>
  {% endif %}

  <form method="POST" action="{{ request.get_full_path }}">
    {% csrf_token %}

    <p>Möchtest Du die Benachrichtigung für <em>{{ notification.pattern }}</em> wirklich löschen?</p>
    <input type="submit" value="Benachrichtigung löschen" />
  </form>

  <p>
    <a href="{% url 'mensautils.canteen:index' %}">Startseite</a> &bull;
    <a href="{% url 'mensautils.canteen:notification' %}">Benachrichtigungen</a>
  </p>
{% endblock content %}

mensautils/canteen/templates/mensautils/login.html
{% extends 'mensautils/base.html' %}
{% load static %}
{% load i18n %}

{% block content %}
  <h1>Einloggen</h1>
  <form method="POST" action="{{ request.get_full_path }}">
    {% csrf_token %}

    <p>Die Anmeldung erfolgt über den Mafiasi-Account.</p>

    <table>
      {{ form }}
    </table>
    <input type="submit" value="{% trans 'Login' %}" />
  </form>
{% endblock content %}

mensautils/canteen/templates/mensautils/mensa.html
{% extends 'mensautils/base.html' %}
{% load static %}
{% load rating %}
{% load canteen %}

{% block content %}
  <h1>Mensa-Speisepläne in Hamburg</h1>

  {% if request.user.is_authenticated %}
    <p>Hallo, <em>{{ request.user.first_name }}</em>.</p>
  {% endif %}

  <div class="row">
    {% for day, canteens in mensa_data.items %}
      <div class="col-md-6">
        <h2>
          {{ day|day_description }}
        </h2>
        {% for canteen, entries in canteens.items %}
          <div id="canteen-{% if day == first_day %}0{% else %}99{% endif %}-{{ canteen.pk }}"
               class="canteen canteen-{{ canteen.pk }}" data-canteennumber="{{ canteen.pk }}">
            <h3>
              {{ canteen }}
              <div class="icons pull-right">
              <a class="up-{{ canteen.pk }} move-link" href="javascript:moveCanteen(-1, {{ canteen.pk }});">
                <span class="icon glyphicon glyphicon-menu-up"></span>
              </a>
              <a class="down-{{ canteen.pk }} move-link" href="javascript:moveCanteen(1, {{ canteen.pk }});">
                <span class="icon glyphicon glyphicon-menu-down"></span>
              </a>
              <a class="delete-{{ canteen.pk }} delete-link" href="javascript:hideCanteen({{ canteen.pk }});">
                <span class="icon glyphicon glyphicon-trash"></span>
              </a>
            {% if day == today %}
              <a href="{% url 'mensautils.canteen:submit_serving' canteen.pk %}">
                <span class="icon glyphicon glyphicon-plus"></span>
              </a>
            {% endif %}
            </div>
            </h3>
            <table class="table table-striped table-hover">
              <tr>
                <th>
                </th>
                {% if day == today %}
                  <th>
                  </th>
                  <th>
                    Bewertung
                  </th>
                {% endif %}
                <th>
                  Preis&nbsp;(€)
                </th>
                <th>
                  Bed.&nbsp;(€)
                </th>
                <th>
                  Gericht
                </th>
                <th>
                </th>
              </tr>
              {% for entry in entries %}
                <tr class="dish-row">
                  <td>
                    {% if entry.dish.vegan %}
                      <span class="vegan">vegan</span>
                    {% elif entry.dish.vegetarian %}
                      <span class="vegetarian">veget.</span>
                    {% endif %}
                  </td>
                  {% if day == today %}
                    <td {% if entry.deprecated %}class="deprecated"{% elif not entry.verified %}class="unverified"{% endif %}>
                      <a class="displayOnHighWidth" href="{% url 'mensautils.canteen:rate_serving' entry.pk %}" title="Bewerten"><span class="glyphicon glyphicon-asterisk"></span></a>
                      <a class="displayOnSmallWidth" href="{% url 'mensautils.canteen:rate_serving' entry.pk %}" title="Bewerten">Bewerten</a>
                    </td>
                    <td 
                        {% if entry.deprecated %}class="deprecated"{% elif not entry.verified %}class="unverified"{% endif %}>
                      {% if entry.average_rating %}
                        {{ entry.average_rating|stars }}<br />
                        ({{ entry.rating_count }} Pers.)
                      {% endif %}
                    </td>
                  {% endif %}
                  <td 
                      {% if entry.deprecated %}class="deprecated"{% elif not entry.verified %}class="unverified"{% endif %}>
                    <span class="displayOnSmallWidth"><strong>Preis:</strong></span>
                    {{ entry.price }}
                  </td>
                  <td 
                      {% if entry.deprecated %}class="deprecated"{% elif not entry.verified %}class="unverified"{% endif %}>
                    <span class="displayOnSmallWidth"><strong>Preis (Bedienstete):</strong></span>
                    {{ entry.price_staff }}
                  </td>
                  <td 
                      {% if entry.deprecated %}class="deprecated"{% elif not entry.verified %}class="unverified"{% endif %}>
                    {{ entry.dish.name }}
                    {% if entry.maybe_deprecated %}
                      <span title="Mindestens ein Nutzer hat dieses Gericht als nicht verfügbar gemeldet.">
                        <em>(???)</em>
                      </span>
                    {% endif %}
                    <hr class="displayBlockOnSmallWidth" />
                  </td>
                  <td>
                    {% if entry.date == today %}
                      {% if not entry.deprecated %}
                        <a href="{% url 'mensautils.canteen:report_deprecation' entry.pk %}">
                          <span class="icon glyphicon glyphicon-trash"></span>
                        </a>
                      {% endif %}
                      {% if not entry.official and not entry.verified %}
                        <a href="{% url 'mensautils.canteen:verify_serving' entry.pk %}">
                          <span class="icon glyphicon glyphicon-ok"></span>
                        </a>
                      {% endif %}
                    {% endif %}
                  </td>
                </tr>
              {% empty %}
                <td colspan="5"><em>Keine Daten.</em></td>
              {% endfor %}
            </table>
          </div>
        {% endfor %}
      </div>
    {% endfor %}
  </div>

  <hr />

  <h4>Legende</h4>
  <p>
    <span class="vegetarian">veget.</span> vegetarisch<br />
    <span class="vegetarian">vegan</span> vegan<br />
    <span class="deprecated">Gericht wurde aus dem Speiseplan entfernt</span><br />
    <span class="unverified">Das Gericht wurde von einem Nutzer vorgeschlagen und noch nicht bestätigt.</span>
  </p>

  <hr />

  <p id="showHiddenCanteensLink"><a href="javascript:showHiddenCanteens();">Ausgeblendete Mensen wieder einblenden</a></p>
  <p><a href="{% url 'mensautils.canteen:notification' %}">Benachrichtigungen konfigurieren</a></p>
  <p>
    Letzte Aktualisierung: {{ last_updated|date:"j. F Y H:i:s" }}<br />
    <a href="{% url 'mensautils.canteen:stats' %}">Statistiken</a> &bull;
    {% if request.user.is_authenticated %}
      <a href="{% url 'logout' %}?next={{ request.get_full_path }}">Abmelden</a>
    {% else %}
      <a href="{% url 'login' %}?next={{ request.get_full_path }}">Anmelden</a>
    {% endif %}
  <p>
  <div class="hidden" style="display: none;">
    <div id="auth">{% if request.user.is_authenticated %}1{% else %}0{% endif %}</div>
    <div id="userConfigAvailable">{% if user_config_available %}1{% else %}0{% endif %}</div>
    <div id="serverCanteenOrder">{{ user_config.0 }}</div>
    <div id="serverHiddenCanteens">{{ user_config.1 }}</div>
  </div>
{% endblock content %}

{% block additional_js %}
  <script type="text/javascript" src="{% static 'mensautils/mensa.js' %}"></script>
{% endblock additional_js %}
{% block additional_css %}
  <link rel="stylesheet" type="text/css" href="{% static 'mensautils/css/base.css' %}" />
{% endblock additional_css %}

mensautils/canteen/templates/mensautils/notifications.html
{% extends 'mensautils/base.html' %}
{% load static %}

{% block content %}
  <h1>Mensa-Speisepläne in Hamburg</h1>

  {% if request.user.is_authenticated %}
    <p>Hallo, <em>{{ request.user.username }}</em>.</p>
  {% endif %}

  <p>Du hast die folgenden Benachrichtigungen konfiguriert:</p>
  <ul>
    {% for notification in notifications %}
      <li>
        {{ notification.pattern }}
        <a href="{% url 'mensautils.canteen:delete_notification' notification.pk %}">
          <span class="glyphicon glyphicon-remove"></span>
        </a>
      </li>
    {% endfor %}
  </ul>
  <p>
    <a href="{% url 'mensautils.canteen:add_notification' %}">
      Benachrichtigung hinzufügen
    </a>
  </p>

  <p>
    <a href="{% url 'mensautils.canteen:index' %}">Startseite</a>
  </p>
{% endblock content %}

mensautils/canteen/templates/mensautils/rate_serving.html
{% extends 'mensautils/base.html' %}
{% load static %}

{% block content %}
  <h1>Mensa-Speisepläne in Hamburg</h1>

  {% if request.user.is_authenticated %}
    <p>Hallo, <em>{{ request.user.username }}</em>.</p>
  {% endif %}

  <form method="POST" action="{{ request.get_full_path }}">
    {% csrf_token %}
    <p>
      Du bewertest gerade <strong>{{ serving.dish.name }}</strong>
      in der Mensa <em>{{ serving.canteen.name }}</em>.
    </p>

    <ul>
      <li>
        <input id="rating_1" name="rating" type="radio" value="1" />
        <label for="rating_1">&#x2605;</label>
      </li>
      <li>
        <input id="rating_2" name="rating" type="radio" value="2" />
        <label for="rating_2">&#x2605;&#x2605;</label>
      </li>
      <li>
        <input id="rating_3" name="rating" type="radio" value="3" />
        <label for="rating_3">&#x2605;&#x2605;&#x2605;</label>
      </li>
      <li>
        <input id="rating_4" name="rating" type="radio" value="4" />
        <label for="rating_4">&#x2605;&#x2605;&#x2605;&#x2605;</label>
      </li>
      <li>
        <input id="rating_5" name="rating" type="radio" value="5" />
        <label for="rating_5">&#x2605;&#x2605;&#x2605;&#x2605;&#x2605;</label>
      </li>
    </ul>
    <p>
      {% for error in form.rating.errors %}
        {{ error }}<br />
      {% endfor %}
      {% for error in form.non_field_errors %}
        {{ error }}<br />
      {% endfor %}
    </p>
    <input type="submit" value="Bewerten" />
  </form>
{% endblock content %}

mensautils/canteen/templates/mensautils/report_deprecation.html
{% extends 'mensautils/base.html' %}
{% load static %}

{% block content %}
  <h1>Mensa-Speisepläne in Hamburg</h1>

  {% if request.user.is_authenticated %}
    <p>Hallo, <em>{{ request.user.username }}</em>.</p>
  {% endif %}

  <form method="POST" action="{{ request.get_full_path }}">
    {% csrf_token %}
    <p>
      Möchtest Du <strong>{{ serving.dish.name }}</strong>
      in der Mensa <em>{{ serving.canteen.name }}</em> wirklich als nicht verfügbar melden?
    </p>

    <input type="submit" value="Als nicht verfügbar melden" />
  </form>
{% endblock content %}

mensautils/canteen/templates/mensautils/statistics.html
{% extends 'mensautils/base.html' %}
{% load static %}

{% block content %}
  <div class="container" style="width: 98%;">
    <h1>Statistiken - Mensa-Speisepläne in Hamburg</h1>

    <div class="row">
      <div class="col-md-6">
        <h2>Die am häufigsten servierten Gerichte</h2>
        <ol>
          {% for dish in most_frequent_dishes %}
            <li>
              {{ dish.name }} ({{ dish.servings__count }} mal serviert)
            </li>
          {% endfor %}
        </ol>
      </div>
      <div class="col-md-6">
        <h2>Die beliebtesten Gerichte</h2>
        <ol>
          {% for dish in most_favored_dishes %}
            <li>
              {{ dish.name }}
              (durchschnittlich {{ dish.servings__ratings__rating__avg }}/5, {{ dish.servings__ratings__rating__count }} mal bewertet)
            </li>
          {% endfor %}
        </ol>
      </div>
    </div>
  </div>

  <p>
    <a href="{% url 'mensautils.canteen:index' %}">Startseite</a>
  </p>
{% endblock content %}

mensautils/canteen/templates/mensautils/submit_serving.html
{% extends 'mensautils/base.html' %}
{% load static %}

{% block content %}
  <h1>Mensa-Speisepläne in Hamburg</h1>

  {% if request.user.is_authenticated %}
    <p>Hallo, <em>{{ request.user.username }}</em>.</p>
  {% endif %}

  <form method="POST" action="{{ request.get_full_path }}">
    {% csrf_token %}
    <p>
      Hier kannst Du ein Gericht, das heute von der Mensa
      <em>{{ serving.canteen.name }}</em> angeboten wird und nicht im
      Speiseplan steht, vorschlagen.
      Bitte stelle sicher, dass noch kein
      entsprechendes Gericht bereits von einem anderen Nutzer
      vorgeschlagen wurde. Übernehme die Gerichtbezeichnung nach Möglichkeit
      wörtlich von dem offiziellen Mensa-Speiseplan vor Ort.<br />
      Die Mensa, für die Du das Gericht angibst, ist <em>{{ canteen.name }}</em>.
    </p>

    <p>
      <label for="id_name">Bezeichnung:</label>
      {{ form.name }}
      {% for error in form.name.errors %}
        {{ error }}<br />
      {% endfor %}
    </p>
    <p>
      <label for="id_name">Preis:</label>
      {{ form.price }}
      {% for error in form.price.errors %}
        {{ error }}<br />
      {% endfor %}
    </p>
    <p>
      <label for="id_name">Preis (Bedienstete):</label>
      {{ form.price_staff }}
      {% for error in form.price_staff.errors %}
        {{ error }}<br />
      {% endfor %}
    </p>
    <p>
      {{ form.vegetarian }}
      <label for="id_vegetarian">Vegetarisch</label>
      {% for error in form.vegetarian.errors %}
        {{ error }}<br />
      {% endfor %}
    </p>
    <p>
      {{ form.vegan }}
      <label for="id_vegan">Vegan</label>
      {% for error in form.vegan.errors %}
        {{ error }}<br />
      {% endfor %}
    </p>
    <p>
      {% for error in form.non_field_errors %}
        {{ error }}<br />
      {% endfor %}
    </p>
    <input type="submit" value="Gericht ergänzen" />
  </form>
{% endblock content %}

mensautils/canteen/templates/mensautils/verify_serving.html
{% extends 'mensautils/base.html' %}
{% load static %}

{% block content %}
  <h1>Mensa-Speisepläne in Hamburg</h1>

  {% if request.user.is_authenticated %}
    <p>Hallo, <em>{{ request.user.username }}</em>.</p>
  {% endif %}

  <form method="POST" action="{{ request.get_full_path }}">
    {% csrf_token %}
    <p>
      Möchtest Du das von einem Nutzer hinzugefügte Gericht
      <strong>{{ serving.dish.name }}</strong> in der Mensa
      <em>{{ serving.canteen.name }}</em> wirklich bestätigen?
    </p>

    <input type="submit" value="Gericht bestätigen" />
  </form>
{% endblock content %}